# Generated by Django 4.1.4 on 2022-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=20)),
                ('pro_desc', models.TextField(max_length=500)),
                ('pro_price', models.CharField(max_length=10)),
                ('pro_release', models.CharField(max_length=10)),
                ('pro_type', models.CharField(max_length=10)),
                ('pro_company', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='gaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('game_Genre', models.CharField(max_length=20)),
                ('game_size', models.CharField(max_length=20)),
                ('game_reqm', models.CharField(max_length=50)),
                ('game_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_date', models.CharField(max_length=10)),
                ('movie_image', models.ImageField(default='default', upload_to='')),
                ('movie_runtime', models.TimeField(default='00')),
                ('movie_director', models.CharField(max_length=50)),
                ('movie_description', models.CharField(max_length=300)),
                ('movie_genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('veh_type', models.IntegerField()),
                ('veh_price', models.BigIntegerField()),
                ('veh_company', models.CharField(max_length=20)),
                ('veh_desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
