# Generated by Django 4.1.4 on 2022-12-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_electronics_pro_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='pro_image2',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='electronics',
            name='pro_image3',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='electronics',
            name='pro_image4',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='electronics',
            name='pro_image5',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='gaming',
            name='game_image1',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='gaming',
            name='game_image2',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='gaming',
            name='game_image3',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='gaming',
            name='game_image4',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='veh_image1',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='veh_image2',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='veh_image3',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='veh_image4',
            field=models.ImageField(default='default', upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='veh_image5',
            field=models.ImageField(default='default', upload_to=''),
        ),
    ]
