# Generated by Django 4.1.4 on 2022-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_electronics_pro_desc_alter_gaming_game_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='game_platform',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
