# Generated by Django 4.1.4 on 2022-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_gaming_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='game_reqm',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='veh_type',
            field=models.CharField(max_length=20),
        ),
    ]
