# Generated by Django 4.1.4 on 2022-12-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_gaming_game_reqm_alter_movie_movie_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_name', models.CharField(max_length=20)),
                ('prod_rel', models.CharField(max_length=20)),
                ('prod_desc', models.TextField(max_length=1500)),
                ('prod_company', models.CharField(max_length=25)),
                ('prod_price', models.CharField(max_length=20)),
                ('prod_type', models.CharField(max_length=25)),
                ('prod_image', models.ImageField(default='default', upload_to='')),
                ('prod_genre', models.CharField(max_length=20)),
                ('prod_platform', models.CharField(max_length=20)),
                ('prod_reqm', models.CharField(max_length=100)),
                ('prod_director', models.CharField(max_length=100)),
                ('pro_runtime', models.CharField(max_length=10)),
            ],
        ),
    ]
